openapi: '3.0.2'
info:
  title: Elevenlabs API
  version: '1.0'
  description: This an definition of the Elevenlabs API for use in code generation.
  termsOfService: https://beta.elevenlabs.io/terms
externalDocs:
  description: API Definition Source
  url: https://docs.elevenlabs.io/api-reference/
servers:
  - url: https://api.elevenlabs.io
tags:
  - name: Text-To-Speech
  - name: Voices
  - name: Samples
  - name: History
  - name: User
paths:
  /v1/text-to-speech/{voice_id}:
    post:
      summary: Text to Speech
      description: Converts text into speech using a voice of your choice and returns audio.
      security:
        - api_key: []
      tags:
        - Text-To-Speech
      parameters:
        - name: voice_id
          description: Voice ID to be used
          in: path
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TextToSpeechRequest'
      responses:
        '200':
          description: OK
          content:
            audio/mpeg:
              schema:
                type: string
                format: binary
        '401':
          description: Unauthorized
  /v1/text-to-speech/{voice_id}/stream:
    post:
      summary: Text to Speech Stream
      description: Converts text into speech using a voice of your choice and returns audio as an audio stream.
      security:
        - api_key: []
      tags:
        - Text-To-Speech
      parameters:
        - name: voice_id
          description: Voice ID to be used
          in: path
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TextToSpeechRequest'
      responses:
        '200':
          description: OK
          content:
            audio/mpeg:
              schema:
                type: string
                format: binary
        '401':
          description: Unauthorized
  /v1/voices:
    get:
      summary: Get Voices
      description: Gets a list of all available voices for a user.
      tags:
        - Voices
      security:
        - api_key: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Voice"
        '401':
          description: Unauthorized
  /v1/voices/settings/default:
    get:
      summary: Get Default Voice Settings
      description: Gets the default settings for voices.
      tags:
        - Voices
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VoiceSettingsResponseModel"
  /v1/voices/{voice_id}/settings:
    get:
      summary: Get Voice Settings
      description: Returns the settings for a specific voice.
      tags:
        - Voices
      security:
        - api_key: []
      parameters:
        - name: voice_id
          description: Voice ID to be used
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VoiceSettingsResponseModel"
        '401':
          description: Unauthorized
  /v1/voices/{voice_id}/settings/edit:
    post:
      summary: Edit Voice Settings
      description: Edit your settings for a specific voice.
      tags:
        - Voices
      security:
        - api_key: []
      parameters:
        - name: voice_id
          description: Voice ID to be used
          in: path
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VoiceSettingsResponseModel'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoiceSettingsEditResponseModel'
        '401':
          description: Unauthorized
  /v1/voices/add:
    post:
      summary: Add Voice
      description: Add a new voice to your collection of voices in VoiceLab.
      tags:
        - Voices
      security:
        - api_key: []
      requestBody:
        content: 
          multipart/form-data: 
            schema: 
              $ref: '#/components/schemas/VoiceRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VoiceResponse'
        '401':
          description: Unauthorized
  /v1/voices/{voice_id}/edit:
    post:
      summary: Edit Voice
      description: Edit a voice created by you.
      tags:
        - Voices
      security:
        - api_key: []
      parameters:
        - name: voice_id
          description: Voice ID to be used
          in: path
          schema:
            type: string
          required: true
      requestBody:
        content: 
          multipart/form-data: 
            schema: 
              $ref: '#/components/schemas/VoiceRequest'
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
  /v1/voices/{voice_id}:
    get:
      summary: Get Voice
      description: Returns metadata about a specific voice.
      tags:
        - Voices
      security:
        - api_key: []
      parameters:
        - name: voice_id
          description: Voice ID to be used
          in: path
          schema:
            type: string
          required: true
        - name: with_settings
          description: If set will return settings information corresponding to the voice, requires authorization.
          in: query
          schema:
            type: boolean
          required: false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Voice'
        '401':
          description: Unauthorized
    delete:
      summary: Delete Voice
      description: Deletes a voice by its ID.
      tags:
        - Voices
      security:
        - api_key: []
      parameters:
        - name: voice_id
          description: Voice ID to be used
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
  /v1/voices/{voice_id}/samples/{sample_id}/audio:
    get:
      summary: Get Audio from Sample
      description: Returns the audio corresponding to a sample attached to a voice.
      tags:
        - Samples
      security:
        - api_key: []
      parameters:
        - name: voice_id
          description: Voice ID to be used
          in: path
          schema:
            type: string
          required: true
        - name: sample_id
          description: Voice ID to be used
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
  /v1/voices/{voice_id}/samples/{sample_id}:
    delete:
      summary: Delete Sample
      description: Removes a sample by its ID.
      tags:
        - Samples
      security:
        - api_key: []
      parameters:
        - name: voice_id
          description: Voice ID to be used
          in: path
          schema:
            type: string
          required: true
        - name: sample_id
          description: Voice ID to be used
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
  /v1/history:
    get:
      summary: Get History
      description: Returns metadata about all your generated audio.
      tags:
        - History
      security:
        - api_key: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/History'
        '401':
          description: Unauthorized
  /v1/history/{history_item_id}/audio:
    get:
      summary: Get Audio from History Item
      description: Returns the audio of an history item.
      tags:
        - History
      security:
        - api_key: []
      parameters:
        - name: history_item_id
          in: path
          description: History item ID to be used
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            audio/mpeg:
              schema:
                type: string
                format: binary
        '401':
          description: Unauthorized
  /v1/history/{history_item_id}:
    delete:
      summary: Delete History Item
      description: Delete a history item by its ID
      tags:
        - History
      security:
        - api_key: []
      parameters:
        - name: history_item_id
          in: path
          description: History item ID to be used
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
        '401':
          description: Unauthorized
  /v1/history/download:
    post:
      summary: Download History Items
      description: Download one or more history items. If one history item ID is provided, we will return a single audio file. If more than one history item IDs are provided, we will provide the history items packed into a .zip file.
      tags:
        - History
      security:
        - api_key: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - "history_item_ids"
              properties:
                history_item_ids:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
                format: binary
        '401':
          description: Unauthorized
  /v1/user:
    get:
      summary: Get User Info
      description: Gets information about the user
      tags:
        - User
      security:
        - api_key: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
        '401':
          description: Unauthorized
  /v1/user/subscription:
    get:
      summary: Get User Subscription Info
      description: Gets extended information about the users subscription.
      tags:
        - User
      security:
        - api_key: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionResponseModel'
        '401':
          description: Unauthorized
components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: xi-api-key
  schemas:
    Voice:
      type: object
      properties:
        voice_id:
          type: string
        name:
          type: string
        samples:
          type: array
          items:
            $ref: "#/components/schemas/Sample"
        category:
          type: string
        fine_tuning:
          $ref: "#/components/schemas/FineTuningResponseModel"
        labels:
          type: string
        description:
          type: string
        preview_url:
          type: string
        available_for_tiers:
          type: array
          items:
            type: string
        settings:
          $ref: '#/components/schemas/VoiceSettingsResponseModel'
    Sample:
      type: object
      properties:
        sample_id:
          type: string
        file_name:
          type: string
        mime_type:
          type: string
        size_bytes:
          type: integer
        hash:
          type: string
    FineTuningResponseModel:
      type: object
      properties:
        model_id:
          type: string
        is_allowed_to_fine_tune:
          type: boolean
        fine_tuning_requested:
          type: boolean
        finetuning_state:
          type: string
        verification_attempts:
          type: array
          items:
            $ref: "#/components/schemas/VerificationAttempts"
        verification_failures:
          type: array
          items:
            type: string
        verification_attempts_count:
          type: integer
        slice_ids:
          type: array
          items:
            type: string
    VerificationAttempts:
      type: object
      properties:
        text:
          type: string
        date_unix:
          type: integer
        accepted:
          type: boolean
        similarity:
          type: number
        levenshtein_distance:
          type: number
        recording:
          $ref: "#/components/schemas/RecordingResponseModel"
    RecordingResponseModel:
      type: object
      properties:
        recording_id:
          type: string
        mime_type:
          type: string
        size_bytes:
          type: integer
        upload_date_unix:
          type: integer
        transcription:
          type: string
    VoiceSettingsResponseModel:
      type: object
      properties:
        stability:
          type: number
        similarity_boost:
          type: number
    VoiceSettingsEditResponseModel:
      type: object
      properties:
        status:
          type: string
    TextToSpeechRequest:
      type: object
      properties:
        text:
          type: string
        voice_settings:
          $ref: '#/components/schemas/VoiceSettingsResponseModel'
    UserInfo:
      type: object
      properties:
        subscription:
          $ref: '#/components/schemas/SubscriptionResponseModel'
        is_new_user:
          type: boolean
        xi_api_key:
          type: string
    SubscriptionResponseModel:
      type: object
      properties:
        tier:
          type: string
        character_count:
          type: integer
        character_limit:
          type: integer
        can_extend_character_limit:
          type: boolean
        allowed_to_extend_character_limit:
          type: boolean
        next_character_count_reset_unix:
          type: integer
        voice_limit:
          type: integer
        professional_voice_limit:
          type: integer
        can_extend_voice_limit:
          type: boolean
        can_use_instant_voice_cloning:
          type: boolean
        can_use_professional_voice_cloning:
          type: boolean
        available_models:
          type: array
          items:
            $ref: '#/components/schemas/Model'
        can_use_delayed_payment_methods:
          type: boolean
        currency:
          type: string
        status:
          type: string
    Model:
      type: object
      properties:
        model_id:
          type: string
        display_name:
          type: string
        supported_language:
          type: string
    History:
      type: object
      properties:
        history_item_id:
          type: string
        voice_id:
          type: string
        voice_name:
          type: string
        text:
          type: string
        date_unix:
          type: integer
        character_count_change_from:
          type: integer
        character_count_change_to:
          type: integer
        content_type:
          type: string
        state:
          type: string
        settings:
          $ref: '#/components/schemas/VoiceSettingsResponseModel'
    VoiceRequest:
      type: object
      required:
          - "name"
          - "files"
      properties:
        name:
          description: The name that identifies this voice. This will be displayed in the dropdown of the website.
          type: string
        files:
          description: Audio files to add to the voice
          type: array
          items:
            type: string
            format: binary
        description:
          description: How would you describe the voice?
          type: string
        labels:
          description: Serialized labels dictionary for the voice.
          type: string
    VoiceResponse:
      type: object
      properties:
        voice_id:
          type: string
